use_frameworks!

platform :ios, '10.0'

target 'LBDecorationLayout_Example' do
  pod 'LBDecorationLayout', :path => '../'

  target 'LBDecorationLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
